### ISSUE TITLE
Where must I put google License Key

### ISSUE THREAD

**Issue by ariesanjaya** [ludei/atomic-plugins-inapps#1]
Hello there, 

I look at this plugin and I think this is great for those who use C++ for their game. This plugin can be a competitor to soomla IAP as that plugin doesn't support cocos2dx 3.3 yet. 
For IOS, its look great. But for android, can you give another example using eclipse project as cocos2dx doesn't support android studio yet.

I want to ask, where do i put google license key for c++ project on android? As I see there is no place for google license key on android.

thank you

**Comment by MortimerGoro** [comment]
Hello,

I have updated the readme with new instructions to sign a build for release (required to test your IAPs on Android) https://github.com/ludei/atomic-plugins-inapps/blob/master/README.md#signing-a-build-for-release.

Regarding eclipse, our demos are based on gradle build system but using eclipse is possible. Here is a summary of the steps to add the plugin to an existing cocos2dx eclipse project (we'll document this better):

* Download c++ prebuilt files https://github.com/ludei/atomic-plugins-inapps/releases/download/1.0.1/cpp.zip 
* Add libInAppService.a (static library) and libsafejni.so (shared library) to your android.mk
* Copy the desired InApp provider java code to your src folder (https://github.com/ludei/atomic-plugins-inapps/tree/master/src/atomic/android)
* Use the API in C++.
* Sign your eclipse project with release keys

**Comment by ariesanjaya** [comment]
Thank You for your reply.
But i still dont understand the implement of googlePlay IAP in this project. I have include all the library. But i dont have a clue how to use it. Maybe I'll wait for the eclipse example so I can submit this IAP to Cocos2dx Community. Keep up for the good work !! :+1:

**Comment by MortimerGoro** [comment]
Yeah, the transition from eclipse to gradle is not easy...

We are going to write a tutorial to integrate this plugin using official cocos2dx project and eclipse. I'll tell you when it's done.  If you can help spreading the word though the cocos2dx community that would be nice.
